In [1]:
import numpy as np

In [5]:
#1(a)
a=np.array([1,2,3,4,5])
add=2+a
add

array([3, 4, 5, 6, 7])

In [7]:
#1(b)
mult=3*a
mult

array([ 3,  6,  9, 12, 15])

In [13]:
#1(c)
div=a/2
div

array([0.5, 1. , 1.5, 2. , 2.5])

In [23]:
#2(a)
arr = np.array([1, 2, 3, 6, 4, 5])
rev_arr=arr[::-1]
rev_arr

array([5, 4, 6, 3, 2, 1])

In [32]:
#3
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

# a) Accessing 1st row, 2nd column (index [0,1])
element_a = arr[0, 1]
# b) Accessing 3rd row, 1st column (index [2,0])
element_b = arr[2, 0]

print(element_a)
print(element_b)


20
70


In [34]:
#4
Your_Name = np.linspace(10, 100, 25)

# Printing array properties
print("Array:", Your_Name)
print("Dimensions:", Your_Name.ndim)   # Number of dimensions
print("Shape:", Your_Name.shape)       # Shape of the array
print("Total elements:", Your_Name.size)  # Total number of elements
print("Data type:", Your_Name.dtype)   # Data type of each element
print("Total bytes consumed:", Your_Name.nbytes)  # Total memory consumed

# Finding transpose using reshape()
transpose_array = Your_Name.reshape(25, 1)
print("\nTranspose using reshape():\n", transpose_array)

# Can we use T attribute?
transpose_T = Your_Name.T
print("\nTranspose using T attribute:\n", transpose_T)

# Checking if both methods give the same result
print("\nAre both transposes identical?", np.array_equal(transpose_array, transpose_T))


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Are both transposes identical? False


In [36]:
#5
ucs420_yourname = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

# Computing required statistics
mean_value = np.mean(ucs420_yourname)    # Mean of all elements
median_value = np.median(ucs420_yourname)  # Median
max_value = np.max(ucs420_yourname)    # Maximum element
min_value = np.min(ucs420_yourname)    # Minimum element
unique_elements = np.unique(ucs420_yourname)  # Unique elements

# Printing computed values
print("Original 2D Array (ucs420_yourname):\n", ucs420_yourname)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)

# Reshaping to (4 rows, 3 columns)
reshaped_ucs420_yourname = ucs420_yourname.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_yourname)

# Resizing to (2 rows, 3 columns)
resized_ucs420_yourname = np.resize(ucs420_yourname, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_yourname)


Original 2D Array (ucs420_yourname):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
